'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ballots
    Public Property BallotsID As Integer
    Public Property ElectionID As Integer
    Public Property BallotsNameTH As String
    Public Property BallotsNameEN As String
    Public Property BallotsDescriptionTH As String
    Public Property BallotsDescriptionEN As String
    Public Property AllowNoChoice As Boolean
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy As String

    Public Overridable Property ElectionVote As ElectionVote
    Public Overridable Property Candidate As ICollection(Of Candidate) = New HashSet(Of Candidate)
    Public Overridable Property MatchElectionBallots As ICollection(Of MatchElectionBallots) = New HashSet(Of MatchElectionBallots)
    Public Overridable Property MatchVoterBallots As ICollection(Of MatchVoterBallots) = New HashSet(Of MatchVoterBallots)

End Class
