'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ElectionType
    Public Property ElectionTypeID As Integer
    Public Property ElectionTypeName As String

    Public Overridable Property ElectionVote As ICollection(Of ElectionVote) = New HashSet(Of ElectionVote)

End Class
