'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ElectionVote
    Public Property ElectionID As Integer
    Public Property ElectionNameTH As String
    Public Property ElectionNameEN As String
    Public Property ElectionDescriptionTH As String
    Public Property ElectionDescriptionEN As String
    Public Property StatusID As Nullable(Of Integer)
    Public Property StatusReport As Nullable(Of Boolean)
    Public Property DateTimeStart As Nullable(Of Date)
    Public Property DateTimeClose As Nullable(Of Date)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy As String

    Public Overridable Property Ballots As ICollection(Of Ballots) = New HashSet(Of Ballots)
    Public Overridable Property ElectionStatus As ElectionStatus
    Public Overridable Property ManageRole As ICollection(Of ManageRole) = New HashSet(Of ManageRole)
    Public Overridable Property MatchElectionBallots As ICollection(Of MatchElectionBallots) = New HashSet(Of MatchElectionBallots)
    Public Overridable Property RegistedVoter As ICollection(Of RegistedVoter) = New HashSet(Of RegistedVoter)
    Public Overridable Property MatchVoterBallots As ICollection(Of MatchVoterBallots) = New HashSet(Of MatchVoterBallots)

End Class
