'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ManageRole
    Public Property AutoID As Integer
    Public Property ElectionID As Integer
    Public Property PSUPassport As String
    Public Property RoleID As Integer
    Public Property IsActived As Boolean

    Public Overridable Property ElectionVote As ElectionVote
    Public Overridable Property ManageRoleStatus As ManageRoleStatus

End Class
