'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MatchVoterBallots
    Public Property AutoID As Integer
    Public Property PSUPassport As String
    Public Property BallotsID As Integer
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property ElectionID As Integer
    Public Property Voted As Nullable(Of Boolean)
    Public Property VotedDate As Nullable(Of Date)

    Public Overridable Property Ballots As Ballots
    Public Overridable Property Voter As Voter
    Public Overridable Property ElectionVote As ElectionVote

End Class
