'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MatchElectionBallots
    Public Property ElectionID As Integer
    Public Property BallotsID As Integer
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy As String

    Public Overridable Property Ballots As Ballots
    Public Overridable Property ElectionVote As ElectionVote

End Class
