'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class PSUOVSEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PSUOVSEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Ballots() As DbSet(Of Ballots)
    Public Overridable Property Candidate() As DbSet(Of Candidate)
    Public Overridable Property ElectionStatus() As DbSet(Of ElectionStatus)
    Public Overridable Property ElectionVote() As DbSet(Of ElectionVote)
    Public Overridable Property Faculty() As DbSet(Of Faculty)
    Public Overridable Property Gender() As DbSet(Of Gender)
    Public Overridable Property ManageRole() As DbSet(Of ManageRole)
    Public Overridable Property ManageRoleStatus() As DbSet(Of ManageRoleStatus)
    Public Overridable Property MatchVoterBallots() As DbSet(Of MatchVoterBallots)
    Public Overridable Property RegistedVoter() As DbSet(Of RegistedVoter)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property Voter() As DbSet(Of Voter)
    Public Overridable Property VoteResult() As DbSet(Of VoteResult)
    Public Overridable Property MatchElectionBallots() As DbSet(Of MatchElectionBallots)
    Public Overridable Property V_Voter() As DbSet(Of V_Voter)

End Class
