'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ReportFacVote
    Public Property AutoID As Integer
    Public Property ElectionID As Integer
    Public Property FacID As Integer
    Public Property FacName As String
    Public Property TotalVote As Integer

    Public Overridable Property ReportVote As ReportVote

End Class
