'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ReportVote
    Public Property ElectionID As Integer
    Public Property TotalFemale As Integer
    Public Property TotalMale As Integer
    Public Property FacVoteID As String

    Public Overridable Property ReportFacVote As ICollection(Of ReportFacVote) = New HashSet(Of ReportFacVote)

End Class
