'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_Voter
    Public Property PSUPassport As String
    Public Property SEX_CODE As String
    Public Property FAC_ID As String
    Public Property TITLE_ID As String
    Public Property STUD_NAME_THAI As String
    Public Property STUD_SNAME_THAI As String
    Public Property STUD_NAME_ENG As String
    Public Property STUD_SNAME_ENG As String
    Public Property FAC_NAME_THAI As String
    Public Property SEX_NAME As String
    Public Property FAC_NAME_ENG As String

End Class
